"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Goalie_1 = require("./Player/player_info/Goalie");
var penalty_enum_1 = require("./Player/enums/penalty_enum");
var position_enum_1 = require("./Player/enums/position_enum");
var Skater_1 = require("./Player/player_info/Skater");
var statistics_int_1 = require("./Player/statistics_int");
var sebastian_aho = new Skater_1.Skater("sebastian", "aho", position_enum_1.positions.center, 94, "Carolina Hurricanes", new statistics_int_1.PlayerStats());
var frederik_anderson = new Goalie_1.Goalie("frederik", "andersen", position_enum_1.positions.goalie, 90, "Carolina Hurricane", new statistics_int_1.GoalieStats());
console.log(sebastian_aho.stats);
sebastian_aho.score_goal(10);
sebastian_aho.take_penalty(penalty_enum_1.penalties.doubleminor);
sebastian_aho.tally_assist(3);
sebastian_aho.tally_assist(4);
console.log(sebastian_aho.stats);
console.log("save %:", frederik_anderson.stats.save_percentage);
frederik_anderson.make_save(5);
console.log("save %:", frederik_anderson.stats.save_percentage);
frederik_anderson.allow_goal(3);
console.log("save %:", frederik_anderson.stats.save_percentage);
frederik_anderson.make_save();
console.log("save %:", frederik_anderson.stats.save_percentage);
